import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./components/Nav/Navbar";
const inter = Inter({ subsets: ["latin"] });
import User_Deta from "./context/User_Deta";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + "   m-auto max-w-5xl "}>
        <div className="bg-slate-100 relative z-0 ">
          <User_Deta>
            <Navbar />
            {children}
          </User_Deta>
        </div>
      </body>
    </html>
  );
}
